[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
  from = "/api/__api_party/rickAndMorty/:splat"
  to = "https://rickandmortyapi.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/__api_party/pokemon/:splat"
  to = "https://pokeapi.co/api/v2/:splat"
  status = 200
  force = true